-- PR field labels matching app/api-services/models/pr.model.ts (SAP_PR_MODULE_LABELS).
-- Do not run automatically. sapsection is HEADER or ITEM so shared names like
-- PR_NUM and CUSTOM_FIELD_* do not collide.
-- Primary key: pk_module_label (moduleid, sapsection, sapname)
-- If ON CONFLICT fails with 42P10 (no unique constraint), add the PK first or
-- use WHERE NOT EXISTS instead.

INSERT INTO public.module_label (moduleid, sapsection, sapname, lablename)
VALUES
  ('PR', 'HEADER', 'PR_NUM', 'PR Number'),
  ('PR', 'HEADER', 'PR_DATE', 'PR Date'),
  ('PR', 'HEADER', 'VEN_CODE', 'Vendor Code'),
  ('PR', 'HEADER', 'VEN_NAME', 'Vendor Name'),
  ('PR', 'HEADER', 'VEN_GST', 'Vendor GST'),
  ('PR', 'HEADER', 'VEN_CONTACT', 'Vendor Contact'),
  ('PR', 'HEADER', 'VEN_EMAIL', 'Vendor Email'),
  ('PR', 'HEADER', 'PUR_ORG', 'Purchasing Organization'),
  ('PR', 'HEADER', 'PUR_GRP', 'Purchasing Group'),
  ('PR', 'HEADER', 'COMP_CODE', 'Company Code'),
  ('PR', 'HEADER', 'TOT_PR_VAL', 'Total PR Value'),
  ('PR', 'HEADER', 'CURRENCY', 'Currency'),
  ('PR', 'HEADER', 'REL_STAT', 'Release Status'),
  ('PR', 'HEADER', 'CREATED_ON', 'Created On'),
  ('PR', 'HEADER', 'CREATED_BY', 'Created By'),
  ('PR', 'HEADER', 'PR_DOC_TYPE', 'PR Document Type'),
  ('PR', 'HEADER', 'PR_DOC_TYPE_DES', 'PR Document Type Description'),
  ('PR', 'HEADER', 'CUSTOM_FIELD_LABEL1', 'Custom Field Label 1'),
  ('PR', 'HEADER', 'CUSTOM_FIELD_VALUE1', 'Custom Field Value 1'),
  ('PR', 'HEADER', 'CUSTOM_FIELD_LABEL2', 'Custom Field Label 2'),
  ('PR', 'HEADER', 'CUSTOM_FIELD_VALUE2', 'Custom Field Value 2'),
  ('PR', 'HEADER', 'CUSTOM_FIELD_LABEL3', 'Custom Field Label 3'),
  ('PR', 'HEADER', 'CUSTOM_FIELD_VALUE3', 'Custom Field Value 3'),
  ('PR', 'HEADER', 'CUSTOM_FIELD_LABEL4', 'Custom Field Label 4'),
  ('PR', 'HEADER', 'CUSTOM_FIELD_VALUE4', 'Custom Field Value 4'),
  ('PR', 'HEADER', 'CUSTOM_FIELD_LABEL5', 'Custom Field Label 5'),
  ('PR', 'HEADER', 'CUSTOM_FIELD_VALUE5', 'Custom Field Value 5'),
  ('PR', 'ITEM', 'PR_NUM', 'PR Number'),
  ('PR', 'ITEM', 'ITEM_NO', 'Item Number'),
  ('PR', 'ITEM', 'VAL_PRC', 'Valuation Price'),
  ('PR', 'ITEM', 'ACC_ASSGN', 'Account Assignment'),
  ('PR', 'ITEM', 'ITEM_CAT', 'Item Category'),
  ('PR', 'ITEM', 'MAT_CODE', 'Material Code'),
  ('PR', 'ITEM', 'SHORT_TEXT', 'Short Text'),
  ('PR', 'ITEM', 'QUANTITY', 'Quantity'),
  ('PR', 'ITEM', 'UOM', 'UOM'),
  ('PR', 'ITEM', 'DELIVERY_DATE', 'Delivery Date'),
  ('PR', 'ITEM', 'MAT_GRP', 'Material Group'),
  ('PR', 'ITEM', 'PLANT_CODE', 'Plant Code'),
  ('PR', 'ITEM', 'STOR_LOC', 'Storage Location'),
  ('PR', 'ITEM', 'REQ_NAME', 'Requester Name'),
  ('PR', 'ITEM', 'REQ_TRACK_NO', 'Tracking Number'),
  ('PR', 'ITEM', 'MPN', 'MPN'),
  ('PR', 'ITEM', 'MANUFACTURER', 'Manufacturer'),
  ('PR', 'ITEM', 'PLAN_DEL_TIME', 'Planned Delivery Time'),
  ('PR', 'ITEM', 'GR_PROC_TIME', 'GR Processing Time'),
  ('PR', 'ITEM', 'FIXED_VENDOR', 'Fixed Vendor'),
  ('PR', 'ITEM', 'INFO_RECORD', 'Info Record'),
  ('PR', 'ITEM', 'DIRECT_VENDOR', 'Direct Vendor'),
  ('PR', 'ITEM', 'CUSTOM_FIELD_LABEL1', 'Custom Field Label 1'),
  ('PR', 'ITEM', 'CUSTOM_FIELD_VALUE1', 'Custom Field Value 1'),
  ('PR', 'ITEM', 'CUSTOM_FIELD_LABEL2', 'Custom Field Label 2'),
  ('PR', 'ITEM', 'CUSTOM_FIELD_VALUE2', 'Custom Field Value 2'),
  ('PR', 'ITEM', 'CUSTOM_FIELD_LABEL3', 'Custom Field Label 3'),
  ('PR', 'ITEM', 'CUSTOM_FIELD_VALUE3', 'Custom Field Value 3'),
  ('PR', 'ITEM', 'CUSTOM_FIELD_LABEL4', 'Custom Field Label 4'),
  ('PR', 'ITEM', 'CUSTOM_FIELD_VALUE4', 'Custom Field Value 4'),
  ('PR', 'ITEM', 'CUSTOM_FIELD_LABEL5', 'Custom Field Label 5'),
  ('PR', 'ITEM', 'CUSTOM_FIELD_VALUE5', 'Custom Field Value 5')
ON CONFLICT (moduleid, sapsection, sapname) DO NOTHING;
