-- PO field labels matching app/api-services/models/po.model.ts (SAP_PO_MODULE_LABELS).
-- Do not run automatically. sapsection is HEADER or ITEM so shared names like
-- PO_NUM, CURRENCY, and CUSTOM_FIELD_* do not collide.
-- Primary key: pk_module_label (moduleid, sapsection, sapname)

INSERT INTO public.module_label (moduleid, sapsection, sapname, lablename)
VALUES
  ('PO', 'HEADER', 'PO_NUM', 'PO Number'),
  ('PO', 'HEADER', 'PO_DATE', 'PO Date'),
  ('PO', 'HEADER', 'VEN_CODE', 'Vendor Code'),
  ('PO', 'HEADER', 'VEN_NAME', 'Vendor Name'),
  ('PO', 'HEADER', 'VEN_GST', 'Vendor GST'),
  ('PO', 'HEADER', 'VEN_CONTACT', 'Vendor Contact'),
  ('PO', 'HEADER', 'VEN_EMAIL', 'Vendor Email'),
  ('PO', 'HEADER', 'PUR_ORG', 'Purchasing Organization'),
  ('PO', 'HEADER', 'PUR_GRP', 'Purchasing Group'),
  ('PO', 'HEADER', 'COMP_CODE', 'Company Code'),
  ('PO', 'HEADER', 'TOT_PO_NET_VAL', 'Total PO Net Value'),
  ('PO', 'HEADER', 'TOT_PO_VAL', 'Total PO Value'),
  ('PO', 'HEADER', 'CURRENCY', 'Currency'),
  ('PO', 'HEADER', 'REL_STAT', 'Release Status'),
  ('PO', 'HEADER', 'CREATED_ON', 'Created On'),
  ('PO', 'HEADER', 'CREATED_BY', 'Created By'),
  ('PO', 'HEADER', 'PUR_DOC_TYPE', 'Purchasing Document Type'),
  ('PO', 'HEADER', 'PUR_DOC_TYPE_DES', 'Purchasing Document Type Description'),
  ('PO', 'HEADER', 'PAY_TERMS_KEY', 'Payment Terms Key'),
  ('PO', 'HEADER', 'PAY_TERMS_KEY_DES', 'Payment Terms Description'),
  ('PO', 'HEADER', 'PO_PDF', 'PO PDF'),
  ('PO', 'HEADER', 'CUSTOM_FIELD_LABEL1', 'Custom Field Label 1'),
  ('PO', 'HEADER', 'CUSTOM_FIELD_VALUE1', 'Custom Field Value 1'),
  ('PO', 'HEADER', 'CUSTOM_FIELD_LABEL2', 'Custom Field Label 2'),
  ('PO', 'HEADER', 'CUSTOM_FIELD_VALUE2', 'Custom Field Value 2'),
  ('PO', 'HEADER', 'CUSTOM_FIELD_LABEL3', 'Custom Field Label 3'),
  ('PO', 'HEADER', 'CUSTOM_FIELD_VALUE3', 'Custom Field Value 3'),
  ('PO', 'HEADER', 'CUSTOM_FIELD_LABEL4', 'Custom Field Label 4'),
  ('PO', 'HEADER', 'CUSTOM_FIELD_VALUE4', 'Custom Field Value 4'),
  ('PO', 'HEADER', 'CUSTOM_FIELD_LABEL5', 'Custom Field Label 5'),
  ('PO', 'HEADER', 'CUSTOM_FIELD_VALUE5', 'Custom Field Value 5'),
  ('PO', 'ITEM', 'PO_NUM', 'PO Number'),
  ('PO', 'ITEM', 'ITEM_NO', 'Item Number'),
  ('PO', 'ITEM', 'ITEM_DESC', 'Item Description'),
  ('PO', 'ITEM', 'PO_QTY', 'PO Quantity'),
  ('PO', 'ITEM', 'ORD_UNIT', 'Order Unit'),
  ('PO', 'ITEM', 'DEL_DATE', 'Delivery Date'),
  ('PO', 'ITEM', 'NET_PRICE', 'Net Price'),
  ('PO', 'ITEM', 'CURRENCY', 'Currency'),
  ('PO', 'ITEM', 'PER_UNIT', 'Price Per Unit'),
  ('PO', 'ITEM', 'PO_PREV_PRICE', 'Previous PO Price'),
  ('PO', 'ITEM', 'PO_PRICE_INCR_PCT', 'PO Price Increase %'),
  ('PO', 'ITEM', 'ITEM_TOTAL', 'Item Total'),
  ('PO', 'ITEM', 'MAT_GRP', 'Material Group'),
  ('PO', 'ITEM', 'PLANT', 'Plant'),
  ('PO', 'ITEM', 'PLANT_DES', 'Plant Description'),
  ('PO', 'ITEM', 'STOR_LOC', 'Storage Location'),
  ('PO', 'ITEM', 'STOR_LOC_DES', 'Storage Location Description'),
  ('PO', 'ITEM', 'REQ_NAME', 'Requester Name'),
  ('PO', 'ITEM', 'HSN', 'HSN'),
  ('PO', 'ITEM', 'CGST_PCT', 'CGST %'),
  ('PO', 'ITEM', 'SGST_PCT', 'SGST %'),
  ('PO', 'ITEM', 'IGST_PCT', 'IGST %'),
  ('PO', 'ITEM', 'CGST_VAL', 'CGST Value'),
  ('PO', 'ITEM', 'SGST_VAL', 'SGST Value'),
  ('PO', 'ITEM', 'IGST_VAL', 'IGST Value'),
  ('PO', 'ITEM', 'MPN', 'MPN'),
  ('PO', 'ITEM', 'CUSTOM_FIELD_LABEL1', 'Custom Field Label 1'),
  ('PO', 'ITEM', 'CUSTOM_FIELD_VALUE1', 'Custom Field Value 1'),
  ('PO', 'ITEM', 'CUSTOM_FIELD_LABEL2', 'Custom Field Label 2'),
  ('PO', 'ITEM', 'CUSTOM_FIELD_VALUE2', 'Custom Field Value 2'),
  ('PO', 'ITEM', 'CUSTOM_FIELD_LABEL3', 'Custom Field Label 3'),
  ('PO', 'ITEM', 'CUSTOM_FIELD_VALUE3', 'Custom Field Value 3'),
  ('PO', 'ITEM', 'CUSTOM_FIELD_LABEL4', 'Custom Field Label 4'),
  ('PO', 'ITEM', 'CUSTOM_FIELD_VALUE4', 'Custom Field Value 4'),
  ('PO', 'ITEM', 'CUSTOM_FIELD_LABEL5', 'Custom Field Label 5'),
  ('PO', 'ITEM', 'CUSTOM_FIELD_VALUE5', 'Custom Field Value 5')
ON CONFLICT (moduleid, sapsection, sapname) DO NOTHING;
