-- Seed public.state. Apply after public_geo_country.sql.

INSERT INTO public.state (countryid, statecode, statename, stateshortname, lastupdateby, lastupdatedate) VALUES
('IND', '1', 'Jammu & Kashmir', 'JK', NULL, NULL),
('IND', '2', 'Himachal Pradesh', 'HP', NULL, NULL),
('IND', '3', 'Punjab', 'PJ', NULL, NULL),
('IND', '4', 'Chandigarh', 'CH', NULL, NULL),
('IND', '5', 'Uttarakhand', 'UT', NULL, NULL),
('IND', '6', 'Haryana', 'HR', NULL, NULL),
('IND', '7', 'Delhi', 'DL', NULL, NULL),
('IND', '8', 'Rajasthan', 'RJ', NULL, NULL),
('IND', '9', 'Uttar Pradesh', 'UP', NULL, NULL),
('IND', '10', 'Bihar', 'BH', NULL, NULL),
('IND', '11', 'Sikkim', 'SK', NULL, NULL),
('IND', '12', 'Arunachal Pradesh', 'AR', NULL, NULL),
('IND', '13', 'Nagaland', 'NL', NULL, NULL),
('IND', '14', 'Manipur', 'MN', NULL, NULL),
('IND', '15', 'Mizoram', 'MM', NULL, NULL),
('IND', '16', 'Tripura', 'TR', NULL, NULL),
('IND', '17', 'Meghalaya', 'ML', NULL, NULL),
('IND', '18', 'Assam', 'AS', NULL, NULL),
('IND', '19', 'West Bengal', 'WB', NULL, NULL),
('IND', '20', 'Jharkhand', 'JH', NULL, NULL),
('IND', '21', 'Orissa', 'OR', NULL, NULL),
('IND', '22', 'Chhattisgarh', 'CG', NULL, NULL),
('IND', '23', 'Madhya Pradesh', 'MP', NULL, NULL),
('IND', '24', 'Gujarat', 'GU', NULL, NULL),
('IND', '25', 'Daman & Diu', 'DD', NULL, NULL),
('IND', '26', 'Dadra & Nagar Haveli', 'DN', NULL, NULL),
('IND', '27', 'Maharashtra', 'MH', NULL, NULL),
('IND', '28', 'Andhra Pradesh', 'AP', NULL, NULL),
('IND', '29', 'Karnataka', 'KR', NULL, NULL),
('IND', '30', 'Goa', 'GO', NULL, NULL),
('IND', '31', 'Lakshadweep', 'LD', NULL, NULL),
('IND', '32', 'Kerala', 'KL', NULL, NULL),
('IND', '33', 'Tamil Nadu', 'TN', NULL, NULL),
('IND', '34', 'Puducherry', 'PC', NULL, NULL),
('IND', '35', 'Andaman & Nicobar Islands', 'AN', NULL, NULL),
('IND', '36', 'Telengana', 'TS', NULL, NULL),
('IND', '37', 'Andrapradesh(New)', 'AP(N)', NULL, NULL),
('IND', 'OTH', 'Other', 'OTH', NULL, NULL)
ON CONFLICT (countryid, statecode) DO NOTHING;
